apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app-deployment
  labels:
    app: healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-app-container
        image: laxg66/capstone02:v1
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
spec:
  type: NodePort
  selector:
    app: healthcare-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8081
    nodePort: 31656
